name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - run: npm ci

      - run: npx nx format:check

      - run: npx nx affected -t lint test build e2e
